services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI: http://localhost:15672 (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:gateway
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on: [rabbitmq]

  users-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:users
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on: [rabbitmq]

  orders-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:orders
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on: [rabbitmq]

  payments-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:payments
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on: [rabbitmq]

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:notification
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on: [rabbitmq]
